# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

x = User.new
x.username = 'admin'
x.first_name = 'admin'
x.last_name = 'admin'
x.email = 'admin@admin.com'
x.password = 'password1'
x.password_confirmation = 'password1'
x.admin = true
x.save

Event.create([
                 {name: '3D Animation', description: "Participants (three teams of two members per state) demonstrate their knowledge of 3D animation technology and design skills to creatively solve the challenge posted on the national TSA website. "},
                 {name: 'Animatronics', description: "Participants (one team per chapter) demonstrate knowledge of mechanical and control systems by designing, fabricating, and controlling an animatronics device that will communicate, entertain, inform, demonstrate and/or illustrate a topic, idea, subject, or concept. Sound, lights, and a surrounding environment must accompany the device."},
                 {name: 'Architectural Design', description: "Participants (one team, or one individual, per chapter; one entry per team or individual) develop a set of architectural plans and related materials for an annual architectural design challenge and construct a physical, as well as a computer-generated model, to accurately depict their design. "},
                 {name: 'Biotechnology Design', description: "Participants (three teams of two to six members per state) select a contemporary biotechnology problem (that relates to the current year’s published topic) and demonstrate understanding of it through documented research, the development of a solution, a display (including an optional model or prototype), and an effective multimedia presentation."},
                 {name: 'Chapter Team', description: "Participants (one team of six members per chapter) take a written parliamentary procedures test in order to qualify for the semifinals, in which they complete an opening ceremony, items of business, parliamentary actions, and a closing ceremony within a specified time period."},
                 {name: 'Children’s Stories', description: "Participants (one team, or one individual, per chapter) create an illustrated children's story of high artistic, instructional, and social value. The narrative may be written in prose or poetry and take the form of a fable, adventure story, or other structure. The physical story book should be of high quality and designed to meet the year’s given theme. The story must have a science, technology, engineering, and mathematics (STEM) focus. "},
                 {name: 'Coding', description: "Participants (one individual, or one team of two to three members, per chapter) respond to an annual coding-related design challenge by developing a software program that will accurately address an on-site problem in a specified, limited amount of time. "},
                 {name: 'Computer-Aided Design (CAD), Architecture', description: "Participants (two individuals per state) use complex computer graphic skills, tools, and processes to develop representations of architectural subjects, such as foundation and/or floor plans, and/or elevation drawings, and/or details of architectural ornamentation or cabinetry. "},
                 {name: 'Computer-Aided Design (CAD), Engineering', description: "Participants (two individuals per state) use complex computer graphic skills, tools, and processes to develop three-dimensional representations of engineering subjects such as a machine part, tool, device, or manufactured product."},
                 {name: 'Computer Integrated Manufacturing (CIM)', description: "Participants (one team of two members per chapter) design, fabricate, and use Computer Integrated Manufacturing (CIM) to create a promotional TSA product that will showcase the current conference city and/or state. "},
                 {name: 'Debating Technological Issues', description: "Participants (three teams of two members per state) work together to prepare for a debate against a team from another chapter. The teams will be instructed to take either the Pro or Con side of a selected subtopic. "},
                 {name: 'Digital Video Production', description: "Participants (three teams per state; an individual may participate solo in this team event) develop a public service announcement and a digital video (with sound) that focuses on the given year’s theme."},
                 {name: 'Dragster Design', description: "Participants (two individuals per chapter; one entry per individual) design, produce a working drawing for, and build a CO2-powered dragster. "},
                 {name: 'Engineering Design', description: "Participants (three teams of three or more members per state) develop a solution to a National Academy of Engineering grand challenge that is posted on the national TSA website. The solution offered will be informed and designed by precise problem definition, thorough research, creativity, experimentation (when possible), and the development of documents and appropriate models (mathematical, graphical, and/or physical prototype/model). Semifinalist teams present and defend their proposed solution to a panel of evaluators."},
                 {name: 'Essays on Technology', description: "Participants (three individuals per state) write a research-based essay (using two or more sources provided on-site) that makes insightful connections about a current technological topic."},
                 {name: 'Extemporaneous Speech', description: "Participants (three individuals per state) verbally communicate their knowledge of technology or TSA subjects by giving a speech after having drawn a card on which a technology or TSA topic is written."},
                 {name: 'Fashion Design and Technology', description: "Participants (three teams of two to four members per state) research, design, and create a portfolio and wearable prototype that reflect the current year’s theme. Semifinalist teams participate in a presentation/interview in which they present their garment designs to judges."},
                 {name: 'Flight Endurance', description: "Participants (two individuals per chapter; one entry per individual) analyze flight principles with a rubber band-powered model aircraft."},
                 {name: 'Future Technology Teacher', description: "Participants (two individuals per chapter) investigate technology education preparation programs in higher education and test their potential as a future technology educator. "},
                 {name: 'Music Production', description: "Participants (three teams per state; an individual may participate solo in this team event) produce an original musical piece that is designed to be played during the national TSA conference opening or closing general sessions. "},
                 {name: 'On Demand Video', description: "Participants (one team of two to six members per chapter) write, shoot, and edit a 60-second video on site during the conference."},
                 {name: 'Photographic Technology', description: "Participants (one individual per chapter) demonstrate understanding of and expertise in using photographic and imaging technology processes to convey a message based on a theme. Semifinalists record images and then utilize graphic editing software to prepare a single final image as a solution to an on-site prompt. "},
                 {name: 'Prepared Presentation', description: "Participants (three individuals per state) deliver an oral presentation, using a digital slide deck, on an topic provided on-site."},
                 {name: 'Promotional Design', description: "Participants (three individuals per state) use computerized graphic communications layout and design skills in the production of a promotional resource for TSA."},
                 {name: 'Scientific Visualization (SciVis)', description: "Participants (three teams per state; an individual may participate solo in this team event) use either 2D or 3D computer graphics tools and design processes to communicate, inform, analyze, and/or illustrate a STEM topic, idea, subject, or concept."},
                 {name: 'Software Development', description: "Participants (one team per chapter) use knowledge of cutting-edge technologies, algorithm design, problem-solving principles, effective communication, and collaborative teamwork to design, implement, test, and document a software development project of educational or social value."},
                 {name: 'STEM Careers', description: "Participants (six individuals per state) develop a specific skill and complete a thorough project about the skill’s relationship to a STEM career area of their choice. Participants research and prepare documentation related to the skill and prepare a video that demonstrates the skill. Semifinalists participate in an on-site interview to discuss the skill developed."},
                 {name: 'Structural Design and Engineering', description: "Participants (one team of two members per chapter) work as a team to build a designated structure that is posted on the TSA website. Teams apply the principles of structural design and engineering through research, design, construction, destructive testing, and assessment to determine the design efficiency of the structure."},
                 {name: 'System Control Technology', description: "Participants (one team of three members per state) work on site to develop a computer-controlled model-solution to a problem, typically one from an industrial setting. Teams analyze the problem, build a computer-controlled mechanical model, program the model, explain the program and mechanical features of the model-solution, and write instructions for evaluators to operate the device."},
                 {name: 'Technology Bowl', description: "Participants (one team of three members per chapter) demonstrate their knowledge of TSA and concepts addressed in the technology content standards by completing a written, objective test; semifinalist teams participate in question/response, head?to?head team competition."},
                 {name: 'Technology Problem Solving', description: "Participants (one team of two individuals per chapter) use their skills in problem solving to develop a finite solution to a problem provided on site."},
                 {name: 'Transportation Modeling', description: "Participants (one individual per chapter) research, design, and produce a scale model of a vehicle that fits the annual design problem."},
                 {name: 'Video Game Design', description: "Participants (three teams per state, with a minimum of two members per team) develop a game that focuses on the subject of their choice. The game must have high artistic, educational, and social value and be interesting, exciting, visually appealing, and intellectually challenging. "},
                 {name: 'Webmaster', description: "Participants (one team of three to five members per chapter) design, build, and launch a website that features the school’s career and technology/engineering program, the TSA chapter, and the chapter’s ability to research and present a given topic pertaining to technology. Semifinalists participate in an on-site interview to demonstrate the knowledge and expertise gained during the development of the website — with an emphasis on web design methods and practices, as well as their research for the annual design topic. "}
             ])